// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function anonClient() {
  const env = globalThis?.process?.env ?? {};
  const url = env.SUPABASE_URL ?? "https://sentinel.invalid";
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "sentinel";
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "\u0642\u0627\u0626\u0645\u0629 \u062E\u062F\u0645\u0627\u062A \u0627\u0644\u0635\u064A\u0627\u0646\u0629 \u0627\u0644\u0645\u062A\u0627\u062D\u0629 \u0641\u064A UberFix (\u0627\u0633\u0645\u060C \u0641\u0626\u0629\u060C \u0633\u0639\u0631 \u062A\u0642\u0631\u064A\u0628\u064A).",
  inputSchema: { limit: z.number().int().min(1).max(200).optional().describe("\u0639\u062F\u062F \u0627\u0644\u0646\u062A\u0627\u0626\u062C (\u0627\u0641\u062A\u0631\u0627\u0636\u064A 100).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const { data, error } = await anonClient().from("services").select("id, code, name, category, description, base_price, currency, is_active").eq("is_active", true).limit(limit ?? 100);
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, services: data ?? [] });
  }
});

// src/lib/mcp/tools/list-branches.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_branches_default = defineTool2({
  name: "list_branches",
  title: "List branches",
  description: "\u0642\u0627\u0626\u0645\u0629 \u0641\u0631\u0648\u0639 UberFix \u0627\u0644\u0639\u0627\u0645\u0629 (\u0627\u0633\u0645\u060C \u0645\u062F\u064A\u0646\u0629\u060C \u0647\u0627\u062A\u0641\u060C \u0625\u062D\u062F\u0627\u062B\u064A\u0627\u062A).",
  inputSchema: { city: z2.string().trim().min(1).optional().describe("\u062A\u0635\u0641\u064A\u0629 \u0628\u0627\u0644\u0645\u062F\u064A\u0646\u0629.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city }) => {
    let q = anonClient().from("branches").select("id, code, name, city, address, phone, latitude, longitude, is_active").eq("is_active", true).limit(200);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, branches: data ?? [] });
  }
});

// src/lib/mcp/tools/find-nearest-branch.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function haversineKm(a, b) {
  const R = 6371;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}
var find_nearest_branch_default = defineTool3({
  name: "find_nearest_branch",
  title: "Find nearest branch",
  description: "\u0625\u0631\u062C\u0627\u0639 \u0623\u0642\u0631\u0628 \u0641\u0631\u0639 UberFix \u0644\u0625\u062D\u062F\u0627\u062B\u064A\u0627\u062A \u0627\u0644\u0639\u0645\u064A\u0644.",
  inputSchema: {
    lat: z3.number().describe("\u062E\u0637 \u0627\u0644\u0639\u0631\u0636."),
    lng: z3.number().describe("\u062E\u0637 \u0627\u0644\u0637\u0648\u0644.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lat, lng }) => {
    const { data, error } = await anonClient().from("branches").select("id, code, name, city, address, phone, latitude, longitude").eq("is_active", true).not("latitude", "is", null).not("longitude", "is", null);
    if (error) return errorResult(error.message);
    const withDist = (data ?? []).map((b) => ({ ...b, distance_km: haversineKm({ lat, lng }, { lat: Number(b.latitude), lng: Number(b.longitude) }) })).sort((a, b) => a.distance_km - b.distance_km);
    return textResult({ nearest: withDist[0] ?? null, top5: withDist.slice(0, 5) });
  }
});

// src/lib/mcp/tools/track-request.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var track_request_default = defineTool4({
  name: "track_maintenance_request",
  title: "Track maintenance request",
  description: "\u062A\u062A\u0628\u0639 \u062D\u0627\u0644\u0629 \u0637\u0644\u0628 \u0635\u064A\u0627\u0646\u0629 \u0639\u0628\u0631 \u0631\u0642\u0645 \u0627\u0644\u0637\u0644\u0628 \u0627\u0644\u0639\u0627\u0645 (\u0628\u062F\u0648\u0646 \u0645\u0639\u0644\u0648\u0645\u0627\u062A \u0634\u062E\u0635\u064A\u0629).",
  inputSchema: {
    request_number: z4.string().trim().min(3).describe("\u0631\u0642\u0645 \u0627\u0644\u0637\u0644\u0628 \u0645\u062B\u0644 UF/MR/YYMMDD/SEQ.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ request_number }) => {
    const { data, error } = await anonClient().rpc("public_track_request", { p_request_number: request_number });
    if (error) return errorResult(error.message);
    if (!data) return errorResult("\u0644\u0645 \u064A\u062A\u0645 \u0627\u0644\u0639\u062B\u0648\u0631 \u0639\u0644\u0649 \u0627\u0644\u0637\u0644\u0628.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/create-request.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var create_request_default = defineTool5({
  name: "create_maintenance_request",
  title: "Create maintenance request",
  description: "\u0625\u0646\u0634\u0627\u0621 \u0637\u0644\u0628 \u0635\u064A\u0627\u0646\u0629 \u0639\u0627\u0645 \u0639\u0628\u0631 \u0628\u0648\u0627\u0628\u0629 UberFix. \u064A\u0639\u064A\u062F \u0631\u0642\u0645 \u0637\u0644\u0628 \u0644\u062A\u062A\u0628\u0639\u0647 \u0644\u0627\u062D\u0642\u0627\u064B.",
  inputSchema: {
    client_name: z5.string().trim().min(2),
    client_phone: z5.string().trim().min(6).describe("\u0647\u0627\u062A\u0641 \u0645\u0635\u0631\u064A \u0628\u0635\u064A\u063A\u0629 \u062F\u0648\u0644\u064A\u0629 \u0645\u0641\u0636\u0644\u0627\u064B."),
    service_type: z5.string().trim().min(2).describe("\u0646\u0648\u0639 \u0627\u0644\u062E\u062F\u0645\u0629 (\u0643\u0647\u0631\u0628\u0627\u0621\u060C \u0633\u0628\u0627\u0643\u0629\u060C \u062A\u0643\u064A\u064A\u0641...)."),
    description: z5.string().trim().min(5),
    location: z5.string().trim().min(2).optional(),
    priority: z5.enum(["low", "medium", "high", "urgent"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (args) => {
    const env = globalThis?.process?.env ?? {};
    const base = env.SUPABASE_URL ?? "";
    const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "";
    if (!base || !anon) return errorResult("Supabase env missing.");
    try {
      const res = await fetch(`${base}/functions/v1/maintenance-gateway`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: anon,
          Authorization: `Bearer ${anon}`
        },
        body: JSON.stringify({ channel: "mcp-public", ...args })
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) return errorResult(`gateway ${res.status}: ${JSON.stringify(body)}`);
      return textResult(body);
    } catch (e) {
      return errorResult(e?.message ?? String(e));
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "uberfix-mcp",
  title: "UberFix",
  version: "0.1.0",
  instructions: "\u0623\u062F\u0648\u0627\u062A \u0639\u0627\u0645\u0629 \u0644\u0646\u0638\u0627\u0645 \u0635\u064A\u0627\u0646\u0629 UberFix. \u062A\u0635\u0641\u062D \u0627\u0644\u062E\u062F\u0645\u0627\u062A \u0648\u0627\u0644\u0641\u0631\u0648\u0639\u060C \u062C\u062F \u0623\u0642\u0631\u0628 \u0641\u0631\u0639\u060C \u0623\u0646\u0634\u0626 \u0637\u0644\u0628 \u0635\u064A\u0627\u0646\u0629 \u062C\u062F\u064A\u062F\u060C \u0623\u0648 \u062A\u062A\u0628\u0651\u0639 \u062D\u0627\u0644\u0629 \u0637\u0644\u0628 \u0628\u0631\u0642\u0645\u0647 \u0627\u0644\u0639\u0627\u0645.",
  tools: [list_services_default, list_branches_default, find_nearest_branch_default, track_request_default, create_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
