-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.annual_grand_winners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  award_year integer NOT NULL,
  story text,
  video_url text,
  certificate_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT annual_grand_winners_pkey PRIMARY KEY (id),
  CONSTRAINT annual_grand_winners_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.app_control (
  id text NOT NULL DEFAULT 'global'::text,
  is_locked boolean NOT NULL DEFAULT false,
  message text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_control_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_name text NOT NULL DEFAULT 'UberFix.shop'::text,
  app_logo_url text,
  company_email text,
  company_phone text,
  company_address text,
  default_currency text DEFAULT 'EGP'::text,
  timezone text DEFAULT 'Africa/Cairo'::text,
  default_language text DEFAULT 'ar'::text,
  allow_self_registration boolean DEFAULT true,
  order_stages jsonb DEFAULT '["new", "in_progress", "completed", "closed"]'::jsonb,
  max_execution_time integer DEFAULT 24,
  allow_edit_after_start boolean DEFAULT false,
  require_manager_approval boolean DEFAULT true,
  show_technicians_on_map boolean DEFAULT true,
  enable_technician_rating boolean DEFAULT true,
  allow_technician_quotes boolean DEFAULT true,
  technician_statuses jsonb DEFAULT '["available", "busy", "offline"]'::jsonb,
  notification_types jsonb DEFAULT '["email", "sms", "in_app"]'::jsonb,
  enable_email_notifications boolean DEFAULT true,
  enable_sms_notifications boolean DEFAULT false,
  enable_in_app_notifications boolean DEFAULT true,
  enable_reminders boolean DEFAULT true,
  notification_templates jsonb DEFAULT '{}'::jsonb,
  theme_mode text DEFAULT 'light'::text,
  primary_color text DEFAULT '#f5bf23'::text,
  secondary_color text DEFAULT '#111'::text,
  background_color text DEFAULT '#d2d2d2'::text,
  map_style text DEFAULT 'roadmap'::text,
  show_footer boolean DEFAULT true,
  custom_css text,
  google_maps_enabled boolean DEFAULT true,
  erpnext_enabled boolean DEFAULT false,
  erpnext_url text,
  smtp_host text,
  smtp_port integer,
  smtp_username text,
  smtp_password text,
  smtp_from_email text,
  enable_2fa boolean DEFAULT false,
  auto_backup_enabled boolean DEFAULT true,
  backup_frequency text DEFAULT 'daily'::text,
  lock_sensitive_settings boolean DEFAULT true,
  session_timeout integer DEFAULT 30,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  appointment_date date NOT NULL,
  appointment_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'rescheduled'::text])),
  property_id uuid,
  vendor_id uuid,
  maintenance_request_id uuid,
  location text,
  notes text,
  reminder_sent boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT appointments_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_values jsonb DEFAULT '{}'::jsonb,
  new_values jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.branch_locations (
  id text NOT NULL,
  branch text NOT NULL,
  address text,
  branch_type text,
  link text,
  icon text,
  latitude text,
  longitude text,
  CONSTRAINT branch_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  city text,
  address text,
  geo jsonb,
  opening_hours text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon_url text,
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities (
  id bigint NOT NULL DEFAULT nextval('cities_id_seq'::regclass),
  name_ar text NOT NULL UNIQUE,
  CONSTRAINT cities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  billing_cycle text,
  pricing_model text,
  eta_tax_profile_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.districts (
  id bigint NOT NULL DEFAULT nextval('districts_id_seq'::regclass),
  city_id bigint NOT NULL,
  name_ar text NOT NULL,
  CONSTRAINT districts_pkey PRIMARY KEY (id),
  CONSTRAINT districts_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.error_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  message text NOT NULL,
  stack text,
  level text NOT NULL DEFAULT 'error'::text CHECK (level = ANY (ARRAY['error'::text, 'warning'::text, 'info'::text])),
  url text,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  error_hash text,
  count integer DEFAULT 1,
  first_seen_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT error_logs_pkey PRIMARY KEY (id),
  CONSTRAINT error_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT error_logs_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  maintenance_request_id uuid,
  category text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  description text,
  expense_date timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.gallery_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  category text NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  tags ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  folder text,
  CONSTRAINT gallery_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hall_of_excellence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  achievement_type text NOT NULL CHECK (achievement_type = ANY (ARRAY['monthly'::text, 'annual'::text, 'legacy'::text])),
  achievement_title text NOT NULL,
  achievement_description text,
  achievement_date date NOT NULL,
  media_urls ARRAY,
  story text,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hall_of_excellence_pkey PRIMARY KEY (id),
  CONSTRAINT hall_of_excellence_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  service_name text NOT NULL,
  description text,
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL UNIQUE,
  customer_name text NOT NULL,
  customer_email text,
  customer_phone text,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'EGP'::text,
  due_date date,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'pending'::text,
  payment_method text,
  payment_reference text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  is_locked boolean NOT NULL DEFAULT false,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT invoices_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.maintenance_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  asset_id uuid,
  opened_by_role text,
  channel text,
  title text NOT NULL,
  description text,
  category_id uuid,
  subcategory_id uuid,
  priority text,
  sla_deadline timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'Open'::mr_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  client_name text,
  client_phone text,
  client_email text,
  location text,
  service_type text,
  estimated_cost numeric,
  actual_cost numeric,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  workflow_stage text DEFAULT 'draft'::text,
  sla_due_date timestamp with time zone,
  assigned_vendor_id uuid,
  vendor_notes text,
  archived_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  property_id uuid,
  latitude double precision,
  longitude double precision,
  sla_accept_due timestamp with time zone,
  sla_arrive_due timestamp with time zone,
  sla_complete_due timestamp with time zone,
  customer_notes text,
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  CONSTRAINT maintenance_requests_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_requests_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT fk_maintenance_requests_assigned_vendor FOREIGN KEY (assigned_vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT maintenance_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT maintenance_requests_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT maintenance_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fk_mr_property FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT maintenance_requests_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id),
  CONSTRAINT fk_mr_company FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fk_mr_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_mr_category FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.maintenance_requests_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  version integer NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  changed_by uuid,
  old_data jsonb DEFAULT '{}'::jsonb,
  new_data jsonb DEFAULT '{}'::jsonb,
  change_summary text,
  workflow_transition text,
  CONSTRAINT maintenance_requests_audit_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_requests_audit_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.maintenance_requests(id),
  CONSTRAINT maintenance_requests_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.message_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  recipient text NOT NULL,
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['sms'::text, 'whatsapp'::text, 'email'::text])),
  message_content text NOT NULL,
  provider text NOT NULL DEFAULT 'twilio'::text,
  status text NOT NULL DEFAULT 'queued'::text,
  external_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_logs_pkey PRIMARY KEY (id),
  CONSTRAINT message_logs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.maintenance_requests(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  is_read boolean DEFAULT false,
  is_starred boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  parent_message_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id),
  CONSTRAINT messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.monthly_excellence_awards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  award_month date NOT NULL,
  award_type text NOT NULL,
  reward_description text,
  reward_value numeric,
  certificate_url text,
  announcement_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monthly_excellence_awards_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_excellence_awards_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info'::text,
  recipient_id uuid NOT NULL,
  sender_id uuid,
  entity_type text,
  entity_id uuid,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sms_sent boolean DEFAULT false,
  whatsapp_sent boolean DEFAULT false,
  message_log_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_message_log_id_fkey FOREIGN KEY (message_log_id) REFERENCES public.message_logs(id)
);
CREATE TABLE public.otp_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text NOT NULL,
  otp_code text NOT NULL,
  action text DEFAULT 'verify'::text,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  role text NOT NULL,
  department_id uuid,
  reports_to uuid,
  position text,
  created_by uuid,
  updated_by uuid,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  first_name text,
  last_name text,
  phone text,
  avatar_url text,
  plan_link text,
  photo_link text,
  iframe_key text,
  link_3d text,
  company_id uuid,
  full_name text DEFAULT COALESCE(((first_name || ' '::text) || last_name), name),
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id),
  CONSTRAINT profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.projects (
  id text NOT NULL,
  name text NOT NULL,
  location text,
  status text NOT NULL DEFAULT 'planning'::text CHECK (status = ANY (ARRAY['planning'::text, 'construction'::text, 'completed'::text])),
  project_type text,
  budget numeric,
  actual_cost numeric,
  start_date date,
  end_date date,
  actual_end_date date,
  magicplan_iframe_url text,
  gallery_url text,
  cover_image_url text,
  progress numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  manager_id text,
  sketch_url text,
  latitude double precision,
  longitude double precision,
  description text,
  company_name text,
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'maintenance'::text, 'inactive'::text, 'sold'::text])),
  address text NOT NULL,
  area numeric,
  value numeric,
  manager_id uuid,
  region_id uuid,
  floors integer,
  rooms integer,
  bathrooms integer,
  parking_spaces integer,
  description text,
  amenities ARRAY,
  maintenance_schedule text,
  last_inspection_date date,
  next_inspection_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  qr_code_data text,
  qr_code_generated_at timestamp with time zone,
  latitude double precision,
  longitude double precision,
  icon_url text,
  code text UNIQUE,
  city_id bigint,
  district_id bigint,
  images ARRAY,
  created_by uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT properties_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT properties_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT properties_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.properties_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  version integer NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  changed_by uuid,
  old_data jsonb DEFAULT '{}'::jsonb,
  new_data jsonb DEFAULT '{}'::jsonb,
  change_summary text,
  CONSTRAINT properties_audit_pkey PRIMARY KEY (id),
  CONSTRAINT properties_audit_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT properties_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  p256dh_key text NOT NULL,
  auth_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.regions (
  id uuid NOT NULL,
  name text NOT NULL,
  code text,
  parent_id uuid,
  level integer NOT NULL,
  coordinates jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT regions_pkey PRIMARY KEY (id),
  CONSTRAINT regions_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.regions(id)
);
CREATE TABLE public.request_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  approval_type text NOT NULL CHECK (approval_type = ANY (ARRAY['request'::text, 'materials'::text, 'completion'::text, 'billing'::text])),
  approver_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  comments text,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT request_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT request_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.request_lifecycle (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  status USER-DEFINED NOT NULL,
  update_type USER-DEFINED NOT NULL,
  updated_by uuid,
  update_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT request_lifecycle_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  request_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  images ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_review_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_review_request FOREIGN KEY (request_id) REFERENCES public.maintenance_requests(id),
  CONSTRAINT reviews_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role text NOT NULL,
  resource text NOT NULL,
  action text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_addons (
  id integer NOT NULL DEFAULT nextval('service_addons_id_seq'::regclass),
  service_item_id integer,
  name character varying NOT NULL,
  description text,
  additional_price numeric NOT NULL,
  duration_hours integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_addons_pkey PRIMARY KEY (id),
  CONSTRAINT service_addons_service_item_id_fkey FOREIGN KEY (service_item_id) REFERENCES public.service_items(id)
);
CREATE TABLE public.service_categories (
  id integer NOT NULL DEFAULT nextval('service_categories_id_seq'::regclass),
  name character varying NOT NULL,
  description text,
  icon character varying,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_items (
  id integer NOT NULL DEFAULT nextval('service_items_id_seq'::regclass),
  subcategory_id integer,
  name character varying NOT NULL,
  description text,
  base_price numeric NOT NULL,
  duration_hours integer,
  is_active boolean DEFAULT true,
  image_url character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_items_pkey PRIMARY KEY (id),
  CONSTRAINT service_items_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.service_subcategories(id)
);
CREATE TABLE public.service_orders (
  id integer NOT NULL DEFAULT nextval('service_orders_id_seq'::regclass),
  customer_id integer NOT NULL,
  technician_id integer,
  service_item_id integer NOT NULL,
  package_id integer,
  total_price numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  location text,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_orders_pkey PRIMARY KEY (id),
  CONSTRAINT service_orders_service_item_id_fkey FOREIGN KEY (service_item_id) REFERENCES public.service_items(id),
  CONSTRAINT service_orders_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.service_packages(id)
);
CREATE TABLE public.service_packages (
  id integer NOT NULL DEFAULT nextval('service_packages_id_seq'::regclass),
  service_item_id integer,
  package_name character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  features jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_packages_pkey PRIMARY KEY (id),
  CONSTRAINT service_packages_service_item_id_fkey FOREIGN KEY (service_item_id) REFERENCES public.service_items(id)
);
CREATE TABLE public.service_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_id uuid NOT NULL,
  branch_id uuid,
  vendor_id uuid,
  price numeric NOT NULL,
  vat_rate numeric,
  CONSTRAINT service_prices_pkey PRIMARY KEY (id),
  CONSTRAINT service_prices_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.service_subcategories (
  id integer NOT NULL DEFAULT nextval('service_subcategories_id_seq'::regclass),
  category_id integer,
  name character varying NOT NULL,
  description text,
  icon character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT service_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subcategory_id uuid,
  code text NOT NULL UNIQUE,
  name_ar text NOT NULL,
  name_en text,
  description_ar text,
  description_en text,
  unit text,
  pricing_type text NOT NULL DEFAULT 'fixed'::text CHECK (pricing_type = ANY (ARRAY['fixed'::text, 'per_unit'::text, 'per_hour'::text, 'per_sqm'::text])),
  base_price numeric DEFAULT 0,
  min_qty numeric DEFAULT 1,
  max_qty numeric,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  icon_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_id uuid,
  name text,
  description text,
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sla_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  priority text NOT NULL,
  accept_within_min integer NOT NULL,
  arrive_within_min integer NOT NULL,
  complete_within_min integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sla_policies_pkey PRIMARY KEY (id),
  CONSTRAINT sla_policies_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.specialization_icons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  name_ar text NOT NULL,
  icon_path text NOT NULL,
  color text DEFAULT '#f5bf23'::text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT specialization_icons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  location text,
  phone text,
  email USER-DEFINED,
  category text,
  status text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  area numeric,
  opening_date timestamp without time zone,
  region_id uuid,
  created_by uuid,
  updated_by uuid,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  map_url text,
  CONSTRAINT stores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.technician_agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  quality_policy_accepted boolean DEFAULT false,
  conduct_policy_accepted boolean DEFAULT false,
  pricing_policy_accepted boolean DEFAULT false,
  customer_respect_policy_accepted boolean DEFAULT false,
  punctuality_policy_accepted boolean DEFAULT false,
  signed_at timestamp with time zone,
  ip_address text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_agreements_pkey PRIMARY KEY (id),
  CONSTRAINT technician_agreements_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id)
);
CREATE TABLE public.technician_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  badge_type text NOT NULL CHECK (badge_type = ANY (ARRAY['gold_monthly'::text, 'crown_annual'::text, 'legacy'::text])),
  badge_title text NOT NULL,
  badge_description text,
  awarded_for text,
  awarded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_badges_pkey PRIMARY KEY (id),
  CONSTRAINT technician_badges_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_badge_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_complaints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  request_id uuid,
  customer_id uuid,
  complaint_type text NOT NULL CHECK (complaint_type = ANY (ARRAY['behavior'::text, 'quality'::text, 'delay'::text, 'pricing'::text, 'no_show'::text, 'other'::text])),
  description text NOT NULL,
  severity text DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'investigating'::text, 'resolved'::text, 'dismissed'::text])),
  resolution text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  penalty_applied numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_complaints_pkey PRIMARY KEY (id),
  CONSTRAINT technician_complaints_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_complaints_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.maintenance_requests(id),
  CONSTRAINT technician_complaints_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id),
  CONSTRAINT technician_complaints_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.technician_coverage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  city_id bigint,
  district_id bigint,
  radius_km numeric DEFAULT 5,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_coverage_pkey PRIMARY KEY (id),
  CONSTRAINT technician_coverage_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_coverage_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT technician_coverage_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.technician_coverage_areas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  city_id bigint,
  district_id bigint,
  radius_km numeric,
  city_name text,
  district_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_coverage_areas_pkey PRIMARY KEY (id),
  CONSTRAINT technician_coverage_areas_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id),
  CONSTRAINT technician_coverage_areas_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT technician_coverage_areas_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.technician_daily_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  visits_assigned integer DEFAULT 0,
  visits_accepted integer DEFAULT 0,
  visits_rejected integer DEFAULT 0,
  visits_cancelled integer DEFAULT 0,
  visits_completed integer DEFAULT 0,
  total_earnings numeric DEFAULT 0.00,
  average_rating numeric DEFAULT 0.00,
  average_response_time integer,
  average_arrival_time integer,
  complaints_received integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_daily_stats_pkey PRIMARY KEY (id),
  CONSTRAINT technician_daily_stats_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  document_type USER-DEFINED NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size integer,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_documents_pkey PRIMARY KEY (id),
  CONSTRAINT technician_documents_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id)
);
CREATE TABLE public.technician_level_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  level text NOT NULL CHECK (level = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text, 'top_rated'::text])),
  achieved_at timestamp with time zone NOT NULL DEFAULT now(),
  requirements_met jsonb NOT NULL,
  previous_level text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_level_history_pkey PRIMARY KEY (id),
  CONSTRAINT technician_level_history_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid UNIQUE,
  current_level text DEFAULT 'technician'::text CHECK (current_level = ANY (ARRAY['technician'::text, 'pro'::text, 'elite'::text])),
  level_updated_at timestamp with time zone DEFAULT now(),
  promotion_history jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_levels_pkey PRIMARY KEY (id),
  CONSTRAINT technician_levels_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_level_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_location (
  technician_id uuid NOT NULL,
  lat double precision,
  lng double precision,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_location_pkey PRIMARY KEY (technician_id),
  CONSTRAINT technician_location_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_monthly_bonuses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  month date NOT NULL,
  commitment_bonus numeric DEFAULT 0.00,
  quality_bonus numeric DEFAULT 0.00,
  time_bonus numeric DEFAULT 0.00,
  top_rated_bonus numeric DEFAULT 0.00,
  super_pro_bonus numeric DEFAULT 0.00,
  total_bonus numeric NOT NULL DEFAULT 0.00,
  visits_completed integer NOT NULL DEFAULT 0,
  average_rating numeric DEFAULT 0.00,
  average_response_time integer,
  average_arrival_time integer,
  cancellation_rate numeric DEFAULT 0.00,
  acceptance_rate numeric DEFAULT 0.00,
  complaints_count integer DEFAULT 0,
  status text DEFAULT 'calculating'::text CHECK (status = ANY (ARRAY['calculating'::text, 'approved'::text, 'paid'::text])),
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_monthly_bonuses_pkey PRIMARY KEY (id),
  CONSTRAINT technician_monthly_bonuses_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid UNIQUE,
  total_tasks integer DEFAULT 0,
  completed_tasks integer DEFAULT 0,
  cancelled_tasks integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  punctuality_score numeric DEFAULT 0,
  quality_score numeric DEFAULT 0,
  professionalism_score numeric DEFAULT 0,
  total_points integer DEFAULT 0,
  complaints_count integer DEFAULT 0,
  excellence_count integer DEFAULT 0,
  last_calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_performance_pkey PRIMARY KEY (id),
  CONSTRAINT technician_performance_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_perf_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_portfolio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  media_urls ARRAY NOT NULL,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text])),
  work_type text,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_portfolio_pkey PRIMARY KEY (id),
  CONSTRAINT technician_portfolio_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  company_name text NOT NULL,
  company_type text CHECK (company_type = ANY (ARRAY['individual'::text, 'small_team'::text, 'company'::text])),
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  preferred_language text DEFAULT 'ar'::text,
  service_email text,
  contact_name text,
  country text DEFAULT 'Egypt'::text,
  city_id bigint,
  district_id bigint,
  street_address text,
  building_no text,
  floor text,
  unit text,
  landmark text,
  accounting_name text,
  accounting_email text,
  accounting_phone text,
  has_insurance boolean DEFAULT false,
  insurance_company_name text,
  policy_number text,
  policy_expiry_date date,
  insurance_notes text,
  pricing_notes text,
  company_model text CHECK (company_model = ANY (ARRAY['local_provider'::text, 'third_party'::text])),
  number_of_inhouse_technicians integer,
  number_of_office_staff integer,
  accepts_emergency_jobs boolean DEFAULT false,
  accepts_national_contracts boolean DEFAULT false,
  additional_notes text,
  agree_terms boolean DEFAULT false,
  agree_payment_terms boolean DEFAULT false,
  terms_accepted_at timestamp with time zone,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'rejected'::text])),
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT technician_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT technician_profiles_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT technician_profiles_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.technician_service_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  service_id integer NOT NULL,
  service_name text,
  standard_price numeric NOT NULL,
  emergency_price numeric,
  night_weekend_price numeric,
  min_job_value numeric,
  material_markup_percent numeric,
  platform_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_service_prices_pkey PRIMARY KEY (id),
  CONSTRAINT technician_service_prices_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id),
  CONSTRAINT technician_service_prices_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service_items(id)
);
CREATE TABLE public.technician_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  service_id uuid NOT NULL,
  experience_years integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_services_pkey PRIMARY KEY (id),
  CONSTRAINT technician_services_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.technician_skill_tests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  specialization text NOT NULL,
  score integer CHECK (score >= 0 AND score <= 100),
  grade text CHECK (grade = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'F'::text])),
  questions_data jsonb DEFAULT '{}'::jsonb,
  answers_data jsonb DEFAULT '{}'::jsonb,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_skill_tests_pkey PRIMARY KEY (id),
  CONSTRAINT technician_skill_tests_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_skill_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  maintenance_request_id uuid,
  task_title text NOT NULL,
  task_description text,
  customer_location text,
  latitude double precision,
  longitude double precision,
  estimated_price numeric,
  estimated_duration integer,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  check_in_at timestamp with time zone,
  check_in_photo text,
  check_out_at timestamp with time zone,
  before_photos ARRAY,
  after_photos ARRAY,
  work_report text,
  actual_duration integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT technician_tasks_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_tasks_maintenance_request_id_fkey FOREIGN KEY (maintenance_request_id) REFERENCES public.maintenance_requests(id),
  CONSTRAINT fk_task_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT fk_task_request FOREIGN KEY (maintenance_request_id) REFERENCES public.maintenance_requests(id)
);
CREATE TABLE public.technician_trades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  category_id integer NOT NULL,
  category_name text,
  years_of_experience integer,
  licenses_or_certifications text,
  can_handle_heavy_projects boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_trades_pkey PRIMARY KEY (id),
  CONSTRAINT technician_trades_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id),
  CONSTRAINT technician_trades_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.technician_training (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid,
  course_type text NOT NULL,
  course_title text NOT NULL,
  status text DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'failed'::text])),
  progress integer DEFAULT 0,
  score integer,
  completed_at timestamp with time zone,
  certificate_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_training_pkey PRIMARY KEY (id),
  CONSTRAINT technician_training_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  request_id uuid,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['earning'::text, 'withdrawal'::text, 'bonus'::text, 'penalty'::text, 'refund'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  platform_fee numeric DEFAULT 0.00,
  net_amount numeric NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT technician_transactions_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_transactions_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.maintenance_requests(id)
);
CREATE TABLE public.technician_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  national_id_front text,
  national_id_back text,
  selfie_image text,
  verification_status text DEFAULT 'pending'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technician_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT technician_verifications_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technician_profiles(id)
);
CREATE TABLE public.technician_wallet (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL UNIQUE,
  balance_current numeric NOT NULL DEFAULT 0.00 CHECK (balance_current >= 0::numeric),
  balance_pending numeric NOT NULL DEFAULT 0.00,
  balance_locked numeric NOT NULL DEFAULT 0.00,
  total_earnings numeric NOT NULL DEFAULT 0.00,
  total_withdrawn numeric NOT NULL DEFAULT 0.00,
  last_withdrawal_at timestamp with time zone,
  minimum_withdrawal numeric NOT NULL DEFAULT 300.00,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_wallet_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wallet_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_wallet_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id)
);
CREATE TABLE public.technician_withdrawals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  amount numeric NOT NULL,
  method text NOT NULL CHECK (method = ANY (ARRAY['vodafone_cash'::text, 'bank_transfer'::text, 'instapay'::text, 'wallet'::text])),
  account_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'rejected'::text, 'cancelled'::text])),
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  processed_by uuid,
  rejection_reason text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_withdrawals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_withdrawal_technician FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_withdrawals_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_withdrawals_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.technician_work_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL,
  city_id bigint,
  district_id bigint,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT technician_work_zones_pkey PRIMARY KEY (id),
  CONSTRAINT technician_work_zones_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.technicians(id),
  CONSTRAINT technician_work_zones_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT technician_work_zones_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.technicians (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  email text,
  specialization text NOT NULL,
  profile_image text,
  rating numeric DEFAULT 0.00 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  status text DEFAULT 'offline'::text CHECK (status = ANY (ARRAY['online'::text, 'busy'::text, 'offline'::text, 'on_route'::text])),
  current_latitude numeric,
  current_longitude numeric,
  location_updated_at timestamp with time zone DEFAULT now(),
  hourly_rate numeric,
  available_from time without time zone,
  available_to time without time zone,
  bio text,
  certifications jsonb DEFAULT '[]'::jsonb,
  service_area_radius numeric DEFAULT 10,
  company_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  application_id uuid,
  code text UNIQUE,
  level text NOT NULL DEFAULT 'certified'::text CHECK (level = ANY (ARRAY['certified'::text, 'senior'::text, 'expert'::text, 'supervisor'::text])),
  verification_center_id uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  icon_url text,
  country_code text,
  city_id bigint,
  district_id bigint,
  primary_service_id uuid,
  standard_rate numeric,
  visit_fee numeric,
  lat double precision,
  lng double precision,
  CONSTRAINT technicians_pkey PRIMARY KEY (id),
  CONSTRAINT technicians_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT technicians_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT technicians_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_roles_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.vendor_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  address text,
  is_active boolean NOT NULL DEFAULT true,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  company_name text,
  specialization ARRAY DEFAULT '{}'::text[],
  phone text,
  email text,
  address text,
  rating numeric DEFAULT 0,
  total_jobs integer DEFAULT 0,
  status text DEFAULT 'active'::text,
  profile_image text,
  experience_years integer DEFAULT 0,
  unit_rate numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  current_latitude double precision,
  current_longitude double precision,
  location_updated_at timestamp with time zone,
  is_tracking_enabled boolean DEFAULT false,
  map_icon text,
  tracking_started_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  last_modified_by uuid,
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES auth.users(id)
);