// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Allow the app to render even if Supabase is not configured by falling back
// to a placeholder client. Features that rely on Supabase will gracefully
// degrade instead of breaking the whole UI.
export const supabaseReady = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!supabaseReady) {
  console.warn(
    'Supabase environment variables are missing. The app will run in offline mode with limited features.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'public-anon-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
