// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supports both Lovable (hardcoded) and self-hosted (env vars) deployments
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://zrrffsjbfkphridqyais.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycmZmc2piZmtwaHJpZHF5YWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzE1NzMsImV4cCI6MjA3MjAwNzU3M30.AwzY48mSUGeopBv5P6gzAPlipTbQasmXK8DR-L_Tm9A";

// Supabase is always ready with direct configuration
export const supabaseReady = true;

// In-memory storage fallback for mobile browsers with restricted localStorage
const memoryStorage: Record<string, string> = {};
const inMemoryStorage = {
  getItem: (key: string) => memoryStorage[key] || null,
  setItem: (key: string, value: string) => { memoryStorage[key] = value; },
  removeItem: (key: string) => { delete memoryStorage[key]; },
};

// Safe localStorage check for private browsing mode compatibility
const getStorage = (): Storage => {
  // Check if we're in a browser environment
  if (typeof window === 'undefined') {
    return inMemoryStorage as unknown as Storage;
  }
  
  try {
    // Check if localStorage exists and is accessible
    if (window.localStorage) {
      const testKey = '__storage_test__';
      window.localStorage.setItem(testKey, testKey);
      window.localStorage.removeItem(testKey);
      return window.localStorage;
    }
  } catch (e) {
    // localStorage not available (private browsing mode or security restrictions)
    console.warn('localStorage not available, using memory storage');
  }
  
  return inMemoryStorage as unknown as Storage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: getStorage() as Storage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  }
);

/**
 * عميل غير مُقيّد بأنواع Database المولّدة.
 * يُستخدم فقط للجداول/الأعمدة القديمة غير المكشوفة في Data API الحالي،
 * حتى يتم توحيد المخطط. لا تستخدمه لأي كود جديد.
 */
export const supabaseLegacy = supabase as unknown as {
  from: (table: string) => any;
  rpc: (fn: string, args?: Record<string, unknown>) => any;
};
